version: "3"
services:
  selenium-hub:
    image: seleniarm/hub:4.20
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4444/status" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - docker-network
  chrome:
    image: seleniarm/node-chromium:124.0
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:5555" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=180
    networks:
      - docker-network
  firefox:
    image: seleniarm/node-firefox
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:5555" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    container_name: node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_INSTANCES=5
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_SESSION_TIMEOUT=180
    networks:
      - docker-network

networks:
  docker-network:
    external: true